export const ADD_TO_ITEMS_LIST = "ADD_TO_ITEMS_LIST";
export const ADD_TO_STORES_LIST = "ADD_TO_STORES_LIST";
export const ADD_TO_RECEIVED_ITEMS_LIST = "ADD_TO_RECEIVED_ITEMS_LIST";
export const REMOVE_FROM_ITEMS_LIST = "REMOVE_FROM_ITEMS_LIST";
export const REMOVE_FROM_STORES_LIST = "REMOVE_FROM_STORES_LIST";
export const REMOVE_FROM_RECEIVED_ITEMS_LIST =
  "REMOVE_FROM_RECEIVED_ITEMS_LIST";
